# https://github.com/denoland/setup-deno

name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        deno:
          [1.x, canary]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: ./
        with:
          deno-version: ${{ matrix.deno }}

      - name: Test Deno
        run: deno test --allow-read